package ar.edu.ArqSoft.rentService.Service.model;

public enum Genero {
	TERROR,COMEDIA,ROMANTICA,DOCUMENTAL,DRAMA, SUSPENSO, HISTORICA, THRILLER, BIOGRAFICAS, ACCION, COMICS, DIBUJO_ANIMADO, INFANTIL;
}
